version: '3'

services: 
  db:
    image: 'postgres:9.5'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment: 
      - POSTGRES_HOST_AUTH_METHOD=trust

  web:
    depends_on: 
      - db
    build: .
    ports:
      - '9292:9292'
    volumes:
      - .:/onebitbot
    environment: 
      - LANG=C.UTF-8
      - API_KEY=

volumes:
  postgres:
